version: "3"
services: 
  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data:/data/db
    ports: 
      - "5432:5432"
  api: 
    container_name: task_management_api
    build: .
    image: task_management_api
    restart: always
    command: npm run start:prod
    volumes:
      - ./dist:/usr/task_management_api/dist
      - ./package.json:/usr/task_management_api/package.json
    ports:
      - "3000:3000"
    links:
      - postgres_db